name: Build Documentation using MkDocs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v5

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material 'mkdocstrings[python]'

      - name: Deploy
        run: |
          mkdocs gh-deploy
